version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

  settings:
    errcheck:
      check-blank: false
    govet:
      enable-all: true
      disable:
        - fieldalignment # Struct field order matches JSON API schema for readability
        - shadow         # Too noisy for idiomatic Go error handling patterns

run:
  timeout: 5m
